name: tests

on:
  pull_request:
    branches:
      - 'master'
      - 'next'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: unit tests
        run: yarn test --run
