name: Push
on:
  push:
    branches:
      - main
jobs:
  push-to-repository:
    name: Push to repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Docker build
        run: docker buildx build --platform linux/arm64/v8 . -t aida --build-arg API_URL=$API_URL --build-arg API_TOKEN=$API_TOKEN
        env:
          API_URL: ${{ secrets.API_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Docker tag
        run: docker tag aida xorob00/personal-automations:latest
      - name: Docker push
        run: docker push xorob00/personal-automations:latest